name: TodoMD
options:
  deploymentTarget:
    iOS: 17.0
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 6.0
    PRODUCT_BUNDLE_IDENTIFIER: com.hans.todomd
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
packages:
  Yams:
    url: https://github.com/jpsim/Yams.git
    from: 6.0.1
targets:
  TodoMDApp:
    type: application
    platform: iOS
    sources:
      - Sources/TodoMDApp
      - Sources/TodoMDCore
    dependencies:
      - package: Yams
      - target: TodoMDShareExtension
        embed: true
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        INFOPLIST_KEY_CFBundleDisplayName: todo.md
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.productivity
        INFOPLIST_KEY_CFBundleURLTypes:
          - CFBundleURLName: com.hans.todomd
            CFBundleURLSchemes:
              - todomd
  TodoMDShareExtension:
    type: app-extension
    platform: iOS
    productName: TodoMDShareExtension
    sources:
      - Sources/TodoMDShareExtension
      - Sources/TodoMDCore
    dependencies:
      - package: Yams
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hans.todomd.share
        INFOPLIST_FILE: Sources/TodoMDShareExtension/Info.plist
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
  TodoMDCoreTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests/TodoMDCoreTests
    dependencies:
      - target: TodoMDApp
