name: TodoMD
options:
  deploymentTarget:
    iOS: 17.0
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 6.0
    PRODUCT_BUNDLE_IDENTIFIER: com.hans.todomd
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
packages:
  Yams:
    url: https://github.com/jpsim/Yams.git
    from: 6.0.1
targets:
  TodoMDApp:
    type: application
    platform: iOS
    sources:
      - Sources/TodoMDApp
      - Sources/TodoMDCore
    dependencies:
      - package: Yams
      - target: TodoMDShareExtension
        embed: true
      - target: TodoMDWidgets
        embed: true
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
        INFOPLIST_KEY_CFBundleDisplayName: todo.md
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.productivity
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
        GOOGLE_OAUTH_CLIENT_ID: ""
        GOOGLE_OAUTH_REDIRECT_URI: "todomd://oauth"
        INFOPLIST_KEY_GOOGLE_OAUTH_CLIENT_ID: $(GOOGLE_OAUTH_CLIENT_ID)
        INFOPLIST_KEY_GOOGLE_OAUTH_REDIRECT_URI: $(GOOGLE_OAUTH_REDIRECT_URI)
        INFOPLIST_KEY_NSRemindersUsageDescription: "todo.md imports tasks from Apple Reminders when you run the import."
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "todo.md uses your location to trigger reminders when you arrive at or leave saved places."
        INFOPLIST_KEY_CFBundleURLTypes:
          - CFBundleURLName: com.hans.todomd
            CFBundleURLSchemes:
              - todomd
  TodoMDShareExtension:
    type: app-extension
    platform: iOS
    productName: TodoMDShareExtension
    sources:
      - Sources/TodoMDShareExtension
      - Sources/TodoMDCore
    dependencies:
      - package: Yams
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hans.todomd.share
        INFOPLIST_FILE: Sources/TodoMDShareExtension/Info.plist
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
  TodoMDWidgets:
    type: app-extension
    platform: iOS
    productName: TodoMDWidgets
    sources:
      - Sources/TodoMDWidgets
      - Sources/TodoMDCore
    dependencies:
      - package: Yams
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hans.todomd.widgets
        INFOPLIST_FILE: Sources/TodoMDWidgets/Info.plist
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0
  TodoMDCoreTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests/TodoMDCoreTests
    dependencies:
      - target: TodoMDApp
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
  TodoMDAppUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - Tests/TodoMDAppUITests
    dependencies:
      - target: TodoMDApp
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES

schemes:
  TodoMDApp:
    build:
      targets:
        TodoMDApp: all
    test:
      targets:
        - name: TodoMDAppUITests
  TodoMDShareExtension:
    build:
      targets:
        TodoMDShareExtension: all
